---
title: "Osrm test"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(osrm)
# Timing library
library(microbenchmark)
```

Tells OSRMr to look for the local instance of OSRM and not the demo server. 
```{r}
options(osrm.server = "http://127.0.0.1:5000/")
```

Stockton Testing. 

SJ Delta College: 37.996592, -121.324200
Stockton Airport: 37.896874, -121.251584
```{r}
test_stockton <- data.frame("id" = c(1,2), "lon" = c(-121.324200,-121.251584), "lat" =  c(37.996592,37.896874))
```

```{r}
osrmTable(test_stockton, measure = "distance")
```




Initial test using demo data and the Berlin map. 
Just make a dataframe using the example
apotheke.df[1:50, c("id","lon","lat")]
```{r}
test <- data.frame("id" = c(1,2), "lon" = c(13.388860,13.385983), "lat" =  c(52.517037,52.496891))
```

Seems like the table is starting to work.
http://127.0.0.1:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true
```{r}
osrmTable(test, measure = "distance")
```

Timing!
```{r}
microbenchmark(NULL, osrmTable(test, measure = "distance"), times=10000L)
```




